### ISSUE TITLE
Support Python 3.x

### ISSUE THREAD

**Issue by ddarren** [VisionInternet/visionLiveSDK-Python#1]
Many platforms such as Heroku seem to be sunsetting support for Python 2.7. Considering that this SDK is probably run on such platforms (it is for us), it would be good if this SDK could run on Python 3.x.

**Comment by ddarren** [comment]
Any updates on upgrading the code to Python 3.x ?

**Comment by dingyuliang** [comment]
@ddarren would you please let me know which Granicus (or VisionInternet) customer you are from? Then i will work with the team to prioritize this.

**Comment by ddarren** [comment]
Hi @dingyuliang - So I represent [Visit Widget](https://visitwidget.com/) and we the provide apps (mobile & web widget) for the Granicus/VisionInternet customer Lewisville TX. We need to use the VistionInterent SDK to sync Lewisville's data over to their branded apps. However, we integrate with over 150 cities and states, and quickly growing, so I imagine we will integrate with more VisionInternet clients in the future.

**Comment by dingyuliang** [comment]
@ddarren, thank you. 
Let me talk with my team and will update you then.

**Comment by dingyuliang** [comment]
@ddarren Since Vision Internet is part of Granicus, I have upgraded the SDK to Python3, and placed it into Granicus organization, please refer to https://github.com/Granicus/visionLiveSDK-Python3. 
I am closing this ticket. 

Please let me know if any question.
